// Generates the auth token for the browser bridge.
// By default uses a deterministic token derived from the machine identity
// (username + hostname) so it's always the same — no sync issues.
// Pass --random for a cryptographically random token instead.

import { createHash, randomBytes } from "node:crypto";
import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir, hostname, userInfo } from "node:os";

const PORT = Number(process.env.BRIDGE_PORT) || 8787;
const useRandom = process.argv.includes("--random");

let token;
if (useRandom) {
  token = randomBytes(24).toString("hex");
  console.log("Generated random token (unique, not machine-derived)");
} else {
  const identity = `claude-browser-bridge:${userInfo().username}@${hostname()}:${PORT}`;
  token = createHash("sha256").update(identity).digest("hex");
  console.log("Generated deterministic token (same every time on this machine)");
}

// 1. Write to ~/.claude/browser-bridge-token (canonical path)
const claudeDir = join(homedir(), ".claude");
if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true });
const canonicalPath = join(claudeDir, "browser-bridge-token");
writeFileSync(canonicalPath, token + "\n");
console.log(`✓ Token written to ${canonicalPath}`);

// 2. Write to server/.bridge-token (legacy fallback)
try {
  writeFileSync(new URL("./.bridge-token", import.meta.url), token + "\n");
  console.log("✓ Token written to server/.bridge-token");
} catch {}

// 3. Write extension/config.js
const searchPaths = [
  new URL("../extension/config.js", import.meta.url).pathname,
  join(process.cwd(), "extension", "config.js"),
];
let extensionWritten = false;
for (const p of searchPaths) {
  try {
    if (existsSync(join(p, "..", "manifest.json"))) {
      writeFileSync(p, `// Generated by gen-token.js — keep out of version control.\nconst BRIDGE_TOKEN = ${JSON.stringify(token)};\n`);
      console.log(`✓ Extension config written to ${p}`);
      extensionWritten = true;
      break;
    }
  } catch {}
}
if (!extensionWritten) {
  console.log(`⚠ Extension directory not found — create extension/config.js manually:`);
  console.log(`  const BRIDGE_TOKEN = "${token}";`);
}

console.log("\n✓ Done. Reload the extension in chrome://extensions to apply.");
