// Generates the shared secret used to authenticate the extension to the
// bridge: writes server/.bridge-token and extension/config.js.
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";

const token = randomBytes(24).toString("hex");
writeFileSync(new URL("./.bridge-token", import.meta.url), token + "\n");
writeFileSync(
  new URL("../extension/config.js", import.meta.url),
  `// Generated by server/gen-token.js — keep out of version control.\nconst BRIDGE_TOKEN = ${JSON.stringify(token)};\n`
);
console.log("Wrote server/.bridge-token and extension/config.js");
console.log("Reload the extension in chrome://extensions to pick up the new token.");
