// Generates the shared secret used to authenticate the extension to the bridge.
// Writes to THREE locations so the token works regardless of install method:
//   1. ~/.claude/browser-bridge-token  (canonical — works with global npm install)
//   2. server/.bridge-token            (legacy — works with cloned repo)
//   3. extension/config.js             (embedded in the Chrome extension)

import { randomBytes } from "node:crypto";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";

const token = randomBytes(24).toString("hex");

// 1. Write to ~/.claude/browser-bridge-token (canonical path)
const claudeDir = join(homedir(), ".claude");
if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true });
const canonicalPath = join(claudeDir, "browser-bridge-token");
writeFileSync(canonicalPath, token + "\n");
console.log(`✓ Token written to ${canonicalPath}`);

// 2. Write to server/.bridge-token (legacy, for local repo use)
try {
  writeFileSync(new URL("./.bridge-token", import.meta.url), token + "\n");
  console.log("✓ Token written to server/.bridge-token");
} catch {
  // May fail if running from global install (read-only node_modules)
}

// 3. Write extension/config.js (search multiple locations)
const searchPaths = [
  new URL("../extension/config.js", import.meta.url).pathname,
  join(process.cwd(), "extension", "config.js"),
];
let extensionWritten = false;
for (const p of searchPaths) {
  try {
    if (existsSync(join(p, "..", "manifest.json"))) {
      writeFileSync(p, `// Generated by gen-token.js — keep out of version control.\nconst BRIDGE_TOKEN = ${JSON.stringify(token)};\n`);
      console.log(`✓ Extension config written to ${p}`);
      extensionWritten = true;
      break;
    }
  } catch {}
}
if (!extensionWritten) {
  console.log(`⚠ Extension directory not found — create extension/config.js manually:`);
  console.log(`  const BRIDGE_TOKEN = "${token}";`);
}

console.log("\n✓ Token generated. Reload the extension in chrome://extensions to apply.");
